### PR TITLE
Add darkMode & fix non-unique mqtt clientId

### PR DESCRIPTION
**Pull request by Zer0x00**
#### New features
- Added darkMode to mitigate the bright flashing of lights

#### Fixes
- Fix non-unique mqtt clientId which was causing issues if you had running 2 instances connected to the same broker
- linted markdown files without changing the appearance as far as possible

### CODE REVIEW

**Comment by normen** [comment]
Cool, thanks! Was the markdown the reason the plugin didn't show the changes of the latest version on install?

**Comment by normen** [comment]
Ah, it still doesn't, gotta look up how that is done..

**Comment by Zer0x00** [comment]
Weird, never noticed that before.

According to [the source code](https://github.com/oznu/homebridge-config-ui-x/blob/master/src/modules/plugins/plugins.service.ts#L505) it looks for a CHANGELOG.md. Assure you that I'm overlooking something.

Maybe someone from the homebridge-config-ui-x team has a clue why it isn't working.

**Comment by normen** [comment]
Ah, I guess it's pulling that from the "releases" tab. People are using github actions to publish.. I usually don't like to make myself too dependent on the repository provider though.. Let's see.

**Pull request merged**
